// =============================================================================
// Markdown utilities — TOC extraction & types
// =============================================================================
// Uses github-slugger (the same package rehype-slug uses internally) so that
// TOC IDs match heading IDs generated by rehype-slug exactly.
// =============================================================================

import GithubSlugger from "github-slugger";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TocEntry {
  id: string;
  text: string;
  level: 2 | 3;
}

// ---------------------------------------------------------------------------
// TOC extraction
// ---------------------------------------------------------------------------

/**
 * Extract h2 and h3 headings from a Markdown string.
 * Returns entries with IDs that match what rehype-slug generates.
 *
 * Uses a simple regex approach to avoid pulling in remark/unist-util-visit
 * as ESM-only transitive dependencies that can break Next.js builds.
 */
export function extractToc(markdown: string): TocEntry[] {
  const entries: TocEntry[] = [];
  const slugger = new GithubSlugger();

  // Match ATX headings (## text or ### text)
  // We exclude h1 — the page header renders the sole <h1>
  const headingRegex = /^(#{2,3})\s+(.+)$/gm;
  let match: RegExpExecArray | null;

  while ((match = headingRegex.exec(markdown)) !== null) {
    const level = match[1].length as 2 | 3;
    const text = match[2].trim();

    if (text) {
      entries.push({
        id: slugger.slug(text),
        text,
        level,
      });
    }
  }

  return entries;
}

// ---------------------------------------------------------------------------
// Markdown rendering (for server-side HTML string use)
// ---------------------------------------------------------------------------

export interface RenderedMarkdown {
  html: string;
  toc: TocEntry[];
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Render Markdown to HTML string with TOC.
 * Use `MarkdownArticle` component for React rendering instead.
 * This function is kept for tests and potential SSR-only use cases.
 */
export function renderMarkdown(markdown: string): RenderedMarkdown {
  const toc = extractToc(markdown);
  const slugger = new GithubSlugger();
  const html = markdown
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean)
    .map((block) => {
      const heading = /^(#{1,6})\s+(.+)$/.exec(block);
      if (heading) {
        const level = heading[1].length;
        const text = heading[2].trim();
        const id = slugger.slug(text);
        return `<h${level} id="${id}">${escapeHtml(text)}</h${level}>`;
      }

      return `<p>${escapeHtml(block)}</p>`;
    })
    .join("");

  return { html, toc };
}
